name: flutter_cached_video_player_plus
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 2.1.3
homepage: https://github.com/woodjobber/flutter_cached_video_player.git

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: CachedVideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web
dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_platform_interface: ^6.2.0
  video_player_web: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"
